/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 * Author: Bradley Chatha
 */

module marmos.docs.staging_generator;

import std.algorithm : map;
import std.array     : array;
import std.logger    : infof;
import std.typecons  : Nullable;

import marmos.converter.json : docToJson;
import marmos.converter.model; // Intentionally everything

import marmos.docs.discover : SiteRoot, RootGroup, MarmosDocModelRootGroup;
import marmos.docs.staging_models;
import marmos.converter.convert; // Intentionally everything

void generateAndEmitNavbar(SiteRoot site)
{
    NavbarRoot navbar;
    foreach(group; site.rootGroups)
        navbar.entries[group.groupName] = rootGroupIndexUrl(group);

    emitFile(site.navbarFile, navbar.docToJson.toPrettyString());
}

void generateAndEmitGroupStagingFiles(SiteRoot site, RootGroup group)
{
    import marmos.docs.discover : loadJsonModel, StagingApiRefGroup;

    if(auto casted = cast(MarmosDocModelRootGroup)group)
    {
        SymbolTree!DocModelRoot[] moduleTrees;

        // Load each module that's part of the API group (TODO: I think eventually there needs to be a pathway for incrementally building up some of this stuff, since large codebases are going to OOM?)
        foreach(filePath; casted.modelFilePaths)
        {
            auto model = loadJsonModel!DocModelRoot(filePath);
            auto tree = SymbolTree!DocModelRoot.fromModel(model.module_, model);
            tree.sortByName();
            moduleTrees ~= tree;
        }

        // Build the navigation tree, but don't output it yet (we need to set hrefs before the emit, which I _think_ might be easier to do as we go along rather than beforehand)
        auto navRoot = buildApiRefNavigation(site, casted, moduleTrees);

        // Build & emit things that can be done in one go.
        foreach(moduleTree; moduleTrees)
        {
            buildAndEmitModuleOverviewPage(group, site, moduleTree, navRoot);
            buildAndEmitChildPages(group, site, moduleTree, navRoot);
        }

        // Output remaining files
        emitFile(site.groupNavFile(group.groupUrlName, "latest"), navRoot.docToJson.toString());
        emitFile(site.groupRootConfigFile(group.groupUrlName), StagingApiRefGroup.ConfigModel().docToJson.toString());
    }
    else
        infof("TODO: Unhandled root group %s", group);
}

/++ Private generators ++/

private GroupNavRoot buildApiRefNavigation(SiteRoot site, MarmosDocModelRootGroup group, SymbolTree!DocModelRoot[] moduleTrees)
{
    GroupNavRoot nav;

    foreach(tree; moduleTrees)
    {
        auto moduleNode = nav.getOrMakeByIdPath(tree.module_.fqnComponents, isGroup: true, category: GroupNavRoot.Node.Category.module_);
        moduleNode.children ~= GroupNavRoot.Node(site.groupNavIndexId, userFacingName: "Overview", isGroup: false);

        // Setup the groups & their user-facing names (rather than letting them use the autogenerated one)
        // (NOTE: The HTML generator will hide groups that don't have any children, so we don't have to have omission logic here)
        nav.getOrMakeByIdPath(site.groupNavAliasesIdPath(tree.module_, []),     isGroup: true).userFacingName = "Aliases";
        nav.getOrMakeByIdPath(site.groupNavClassesIdPath(tree.module_, []),     isGroup: true).userFacingName = "Classes";
        nav.getOrMakeByIdPath(site.groupNavConstantsIdPath(tree.module_, []),   isGroup: true).userFacingName = "Enum Constants";
        nav.getOrMakeByIdPath(site.groupNavEnumsIdPath(tree.module_, []),       isGroup: true).userFacingName = "Enums";
        nav.getOrMakeByIdPath(site.groupNavFunctionsIdPath(tree.module_, []),   isGroup: true).userFacingName = "Functions";
        nav.getOrMakeByIdPath(site.groupNavStructsIdPath(tree.module_, []),     isGroup: true).userFacingName = "Structs";
        nav.getOrMakeByIdPath(site.groupNavTemplatesIdPath(tree.module_, []),   isGroup: true).userFacingName = "Templates";
        nav.getOrMakeByIdPath(site.groupNavUnionsIdPath(tree.module_, []),      isGroup: true).userFacingName = "Unions";
        nav.getOrMakeByIdPath(site.groupNavVariablesIdPath(tree.module_, []),   isGroup: true).userFacingName = "Variables";

        // Further nodes are automatically added as their pages are generated, the above are just the ones we need to manually tweak fields of.
    }

    return nav;
}

private void buildAndEmitModuleOverviewPage(
    RootGroup group,
    SiteRoot site, 
    SymbolTree!DocModelRoot moduleTree, 
    scope ref GroupNavRoot nav,
)
{
    import std.string : join;

    ApiPageRoot page;

    // Module name & comment
    page.add(ApiPageHeader(level: 1, htmlId: "", "Module "~moduleTree.module_.fqnComponents.join(".")));
    page.add(convertDocComment(moduleTree.module_.comment, page.sidebarHeaders));

    // Symbol tables
    insertSymbolTables(site, page, moduleTree, nav);

    // Emit file, and set the navigation href
    const indexFilePath = site.groupModuleIndexFile(group.groupUrlName, moduleTree.module_, "latest");
    const indexFileHref = site.groupModuleIndexHref(group.groupUrlName, moduleTree.module_, "latest");

    emitFile(indexFilePath, docToJson(page).toString());
    nav.getOrMakeByIdPath(moduleTree.module_.fqnComponents ~ site.groupNavIndexId, isGroup: false).href = indexFileHref;
    nav.getOrMakeByIdPathHidden(moduleTree.module_.fqnComponents).href = indexFileHref;
}

private void buildAndEmitChildPages(DocModelT)(
    RootGroup group,
    SiteRoot site,
    SymbolTree!DocModelT tree,
    scope ref GroupNavRoot nav,
    bool hideNavItem = false,
)
{
    LeafT[] findOverrides(LeafT)(LeafT mainLeaf, LeafT[] otherLeaves, scope ref size_t i)
    {
        const start = i + 1;
        while(i + 1 < otherLeaves.length && otherLeaves[i + 1].memberComponents == mainLeaf.memberComponents)
            i++;

        if(start > i)
            return [];
        return otherLeaves[start..i];
    }

    // NOTE: _Technically_ aggregate types can also have multiple definitions due to conditional compliation... but TODO: for now the last one wins.
    foreach(item; tree.classes) buildAndEmitAggregatePage!"Classes"(group, site, item, nav, hideNavItem);
    foreach(item; tree.structs) buildAndEmitAggregatePage!"Structs"(group, site, item, nav, hideNavItem);
    foreach(item; tree.unions) buildAndEmitAggregatePage!"Unions"(group, site, item, nav, hideNavItem);
    foreach(item; tree.templates) buildAndEmitAggregatePage!"Templates"(group, site, item, nav, hideNavItem);
    for(size_t i = 0; i < tree.aliases.length; i++) 
    {
        auto item = tree.aliases[i];
        auto overrides = findOverrides(item, tree.aliases, i); // Modifies `i`
        buildAndEmitLeafPage!"Aliases"(group, site, item, overrides, nav, hideNavItem);
    }
    for(size_t i = 0; i < tree.functions.length; i++) 
    {
        auto item = tree.functions[i];
        auto overrides = findOverrides(item, tree.functions, i); // Modifies `i`
        buildAndEmitLeafPage!"Functions"(group, site, item, overrides, nav, hideNavItem);
    }
    for(size_t i = 0; i < tree.constants.length; i++) 
    {
        auto item = tree.constants[i];
        auto overrides = findOverrides(item, tree.constants, i); // Modifies `i`
        buildAndEmitLeafPage!"Constants"(group, site, item, overrides, nav, hideNavItem);
    }
    for(size_t i = 0; i < tree.enums.length; i++) 
    {
        auto item = tree.enums[i];
        auto overrides = findOverrides(item, tree.enums, i); // Modifies `i`
        buildAndEmitLeafPage!"Enums"(group, site, item, overrides, nav, hideNavItem);
    }
    for(size_t i = 0; i < tree.variables.length; i++) 
    {
        auto item = tree.variables[i];
        auto overrides = findOverrides(item, tree.variables, i); // Modifies `i`
        buildAndEmitLeafPage!"Variables"(group, site, item, overrides, nav, hideNavItem);
    }
}

private void buildAndEmitAggregatePage(string TypeName, DocModelT)(
    RootGroup group,
    SiteRoot site,
    SymbolTree!DocModelT tree,
    scope ref GroupNavRoot nav,
    bool hideNavItem = false,
)
{
    import std.string : join;

    static if(is(typeof(tree.model) : MaybeTemplated!Underlying, Underlying))
        auto model = tree.model.model;
    else
        auto model = tree.model;

    ApiPageRoot page;

    // Name; code overview, and then documentation
    page.add(ApiPageHeader(level: 1, htmlId: "", TypeName~" "~tree.memberComponents.join(".")));
    page.add(buildDlangCodeBlock(site, tree));
    page.add(convertDocComment(model.comment, page.sidebarHeaders));

    // Symbol tables
    insertSymbolTables(site, page, tree, nav);

    // Emit file, and set the navigation href
    const indexFilePath = __traits(getMember, site, "groupModule"~TypeName~"IndexFile")(group.groupUrlName, tree.module_, tree.memberComponents, "latest");
    const indexFileHref = __traits(getMember, site, "groupModule"~TypeName~"IndexHref")(group.groupUrlName, tree.module_, tree.memberComponents, "latest");
    auto  indexIdPath   = __traits(getMember, site, "groupNav"~TypeName~"IdPath")(tree.module_, tree.memberComponents);

    emitFile(indexFilePath, docToJson(page).toString());
    nav.getOrMakeByIdPath(indexIdPath, isGroup: false, isHidden: hideNavItem).href = indexFileHref;
    nav.getOrMakeByIdPathHidden(tree.module_.fqnComponents ~ tree.memberComponents).href = indexFileHref;

    // Generate pages for nested types.
    buildAndEmitChildPages(group, site, tree, nav, hideNavItem: true);
}

private void buildAndEmitLeafPage(string TypeName, DocModelT)(
    RootGroup group,
    SiteRoot site,
    SymbolLeaf!DocModelT leaf,
    SymbolLeaf!DocModelT[] overrides,
    scope ref GroupNavRoot nav,
    bool hideNavItem = false,
)
{
    import std.conv   : to;
    import std.string : join;

    static if(is(typeof(leaf.model) : MaybeTemplated!Underlying, Underlying))
        auto model = leaf.model.model;
    else
        auto model = leaf.model;

    ApiPageRoot page;

    // Name; code overview, and then documentation
    page.add(ApiPageHeader(level: 1, htmlId: "", TypeName~" "~leaf.memberComponents.join(".")));
    page.add(buildDlangCodeBlock(site, leaf));
    page.add(convertDocComment(model.comment, page.sidebarHeaders));

    // Do the same for any overrides
    foreach(i, override_; overrides)
    {
        static if(is(typeof(override_.model) : MaybeTemplated!Underlying, Underlying))
            auto overrideModel = override_.model.model;
        else
            auto overrideModel = override_.model;

        auto header = ApiPageHeader(level: 1, htmlId: "override-"~i.to!string, "Override "~TypeName~" "~override_.memberComponents.join("."));
        page.add(header);
        page.sidebarHeaders ~= ApiPageRoot.SidebarHeader(header.htmlId, "Override "~i.to!string, nestingLevel: 0);
        page.add(buildDlangCodeBlock(site, override_));
        page.add(convertDocComment(overrideModel.comment, page.sidebarHeaders));
    }

    // Emit file, and set the navigation href
    const indexFilePath = __traits(getMember, site, "groupModule"~TypeName~"IndexFile")(group.groupUrlName, leaf.module_, leaf.memberComponents, "latest");
    const indexFileHref = __traits(getMember, site, "groupModule"~TypeName~"IndexHref")(group.groupUrlName, leaf.module_, leaf.memberComponents, "latest");
    auto  indexIdPath   = __traits(getMember, site, "groupNav"~TypeName~"IdPath")(leaf.module_, leaf.memberComponents);

    emitFile(indexFilePath, docToJson(page).toString());
    nav.getOrMakeByIdPath(indexIdPath, isGroup: false, isHidden: hideNavItem).href = indexFileHref;
    nav.getOrMakeByIdPathHidden(leaf.module_.fqnComponents ~ leaf.memberComponents).href = indexFileHref;
}

private void insertSymbolTables(DocModelT)(
    SiteRoot site,
    scope ref ApiPageRoot page,
    SymbolTree!DocModelT symbolTree, 
    scope ref GroupNavRoot nav,
)
{
    import std.ascii : toUpper;

    // Define headers separately, so we can access their IDs easier
    static struct Headers
    {
        /++ 
            These MUST have the same names as the symbols trees/leaves inside of SymbolTree.

            A bit of metaprogramming is used to automatically omit the header + symbol table if the tree of the same name is empty.
        ++/
        ApiPageHeader aliases   = ApiPageHeader(level: 2, htmlId: "aliases",    "Aliases");
        ApiPageHeader classes   = ApiPageHeader(level: 2, htmlId: "classes",    "Classes");
        ApiPageHeader constants = ApiPageHeader(level: 2, htmlId: "constants",  "Constants");
        ApiPageHeader enums     = ApiPageHeader(level: 2, htmlId: "enums",      "Enums");
        ApiPageHeader functions = ApiPageHeader(level: 2, htmlId: "functions",  "Functions");
        ApiPageHeader structs   = ApiPageHeader(level: 2, htmlId: "structs",    "Structs");
        ApiPageHeader templates = ApiPageHeader(level: 2, htmlId: "templates",  "Templates");
        ApiPageHeader unions    = ApiPageHeader(level: 2, htmlId: "unions",     "Unions");
        ApiPageHeader variables = ApiPageHeader(level: 2, htmlId: "variables",  "Variables");
    }
    Headers headers;

    page.sidebarHeaders ~= ApiPageRoot.SidebarHeader("", "Symbols", nestingLevel: 0);

    // Symbol tables
    // If e.g. `symbolTree.classes` isn't empty, then add `header.classes` and the symbol table for `tree.classes`.
    static foreach(MemberName; __traits(allMembers, Headers))
    {{
        auto header = __traits(getMember, headers, MemberName);
        auto trees = __traits(getMember, symbolTree, MemberName);
        auto getNavId = &__traits(getMember, site, "groupNav"~MemberName[0].toUpper~MemberName[1..$]~"IdPath");
        if(trees.length > 0)
        {
            page.add(header);
            page.add(buildApiPageTable(trees, getNavId));
            page.sidebarHeaders ~= ApiPageRoot.SidebarHeader(header.htmlId, header.text, nestingLevel: 1);
        }
    }}
}

/++ Other generator helpers ++/

ApiPageTable buildApiPageTable(TreeOrLeafT)(
    TreeOrLeafT[] nodes,
    scope string[] delegate(DocModule, string[]) getNavId,
)
if(is(TreeOrLeafT : SymbolTree!_, _) || is(TreeOrLeafT : SymbolLeaf!_, _))
    => ApiPageTable(
        columns: [ApiPageSpan(text: "Name").asComponent, ApiPageSpan(text: "Description").asComponent],
        rows: nodes.map!((node) {
            static if(is(typeof(node.model) : MaybeTemplated!Underlying, Underlying))
                auto model = node.model.model;
            else
                auto model = node.model;

            return [
                // Name
                ApiPageSpan(text: model.name).asNavLink(idPath: getNavId(node.module_, node.memberComponents)),

                // Description
                getOverviewComment(model.comment)
            ];
        }).array
    );

/++ Doc comment converters ++/

private ApiPageComponent[] convertDocComment(Nullable!DocComment comment, scope ref ApiPageRoot.SidebarHeader[] sidebarHeaders)
    => comment.isNull ? [] : convertDocComment(comment.get, sidebarHeaders);

private ApiPageComponent[] convertDocComment(DocComment comment, scope ref ApiPageRoot.SidebarHeader[] sidebarHeaders)
{
    import std.sumtype : match;

    if(comment.sections.length == 0)
        return null;

    ApiPageComponent[] result;

    void convertParagraph(DocCommentParagraphBlock block, scope ref ApiPageComponent[] components)
    {
        ApiPageParagraph paragraph;

        foreach(sumType; block.inlines)
        {
            paragraph.components ~= sumType.match!(
                (DocCommentTextInline inline) => ApiPageSpan(text: inline.text).asComponent,
                (DocCommentBoldInline inline) => ApiPageSpan(text: inline.text, style: [ApiPageSpan.Style.bold]).asComponent,
                (DocCommentItalicInline inline) => ApiPageSpan(text: inline.text, style: [ApiPageSpan.Style.italic]).asComponent,
                (DocCommentCodeInline inline) => ApiPageSpan(text: inline.text, style: [ApiPageSpan.Style.code]).asComponent,
                (DocCommentLinkInline inline) => ApiPageSpan(text: inline.text).asHrefLink(inline.url),
            );
        }

        components ~= paragraph.asComponent;
    }

    void convertList(ListT)(ListT list, bool isOrdered, scope ref ApiPageComponent[] components)
    {
        if(list.length == 0)
            return;

        static struct StackItem
        {
            ApiPageList list;
            uint level;
        }
        StackItem[] stack = [StackItem(ApiPageList(isOrdered: isOrdered), level: list[0].nestingLevel)];

        foreach(item; list)
        {
            // Add or pop a list into the stack as needed.
            if(item.nestingLevel > stack[$-1].level)
                stack ~= StackItem(ApiPageList(isOrdered: isOrdered), level: item.nestingLevel);
            else if(item.nestingLevel < stack[$-1].level)
            {
                stack[$-2].list.items ~= stack[$-1].list.asComponent;
                stack = stack[0..$-1];
            }

            // Then begin to populate it/continue to append to it
            convertParagraph(item.block, stack[$-1].list.items);
        }

        // Collapse the stack into a single remaining list
        while(stack.length > 1)
        {
            stack[$-2].list.items ~= stack[$-1].list.asComponent;
            stack = stack[0..$-1];
        }

        components ~= stack[0].list.asComponent;
    }

    auto docHeader = ApiPageHeader(level: 2, htmlId: "documentation", "Documentation");
    sidebarHeaders ~= ApiPageRoot.SidebarHeader(docHeader.htmlId, docHeader.text, nestingLevel: 0);
    result ~= docHeader.asComponent;

    foreach(section; comment.sections)
    {
        // Add header if it's not the default section (which is covered by the Documentation header instead)
        if(section.title != "__default")
        {
            auto header = ApiPageHeader(level: 3, htmlId: section.title, section.title); // TODO: Make sure the ID is converted into something URL friendly
            sidebarHeaders ~= ApiPageRoot.SidebarHeader(header.htmlId, header.text, nestingLevel: 1);
            result ~= header.asComponent;
        }

        foreach(sumType; section.blocks)
        {
            sumType.match!(
                (DocCommentParagraphBlock block) {
                    convertParagraph(block, result);
                },
                (DocCommentOrderedListBlock block) {
                    convertList(block.items, isOrdered: true, result);
                },
                (DocCommentUnorderedListBlock block) {
                    convertList(block.items, isOrdered: false, result);
                },
                (DocCommentEqualListBlock block) {
                    // TODO
                },
            );
        }
    }

    return result;
}

private ApiPageComponent getOverviewComment(DocCommentT)(DocCommentT comment)
{
    ApiPageRoot.SidebarHeader[] fakeSidebar;
    auto components = convertDocComment(comment, fakeSidebar);
    if(components.length == 0)
        return ApiPageSpan().asComponent;

    return ApiPageSpan(text: "TODO!").asComponent;
}

private ApiPageDlangCodeComponent getOverviewCommentForCode(DocCommentT)(DocCommentT comment)
{
    ApiPageRoot.SidebarHeader[] fakeSidebar;
    auto components = convertDocComment(comment, fakeSidebar);
    if(components.length == 0)
        return ApiPageCodeText(ApiPageCodeText.Syntax.comment, "///").asCodeComponent;

    return ApiPageCodeText(ApiPageCodeText.Syntax.comment, "/// TODO").asCodeComponent;
}

/++ Code block generation ++/

private immutable STORAGE_CLASSES_BEFORE_FUNCTION_NAME = [
    DocStorageClass.abstract_,
    DocStorageClass.auto_,
    DocStorageClass.autoref,
    DocStorageClass.final_,
    DocStorageClass.override_,
    DocStorageClass.shared_,
    DocStorageClass.static_,
    DocStorageClass.synchronized_,
];

private ApiPageDlangCode buildDlangCodeBlock(TreeOrLeafT)(SiteRoot site, TreeOrLeafT treeOrLeaf)
{
    ApiPageDlangCode code;
    appendCode(site, treeOrLeaf, code);

    return code;
}

private void appendCode(SiteRoot site, SymbolTree!(MaybeTemplated!DocClass) doc, scope ref ApiPageDlangCode code, bool isNestedOverview = false)
{
    DocClass model = doc.model.model;

    if(!isNestedOverview)
        appendModuleStatement(site, doc.module_, code);

    appendLinkage(model.linkage, code);
    appendVisibility(model.visibility, code);
    appendAggregateStorageClasses(model.storageClasses, code);
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "class "));
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, doc.memberComponents[$-1]).asNavLink(
        site.groupNavClassesIdPath(doc.module_, doc.memberComponents)
    ));

    if(!doc.model.eponymousTemplate.isNull)
    {
        auto tpl = doc.model.eponymousTemplate.get;
        appendTemplateParams(tpl.originalParameters.length > 0 ? tpl.originalParameters : tpl.parameters, code, forceSingleLine: isNestedOverview);
    }

    if(!model.baseClass.isNull || model.interfaces.length > 0)
    {
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " : "));

        if(!model.baseClass.isNull)
            appendTypeRef(model.baseClass.get, code, forceSingleLine: isNestedOverview);

        foreach(i, inter; model.interfaces)
        {
            if(i > 0 || !model.baseClass.isNull)
                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ", "));

            appendTypeRef(inter, code, forceSingleLine: isNestedOverview);
        }
    }

    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "{"));
    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeIndent());

    appendSymbolTreeMembersGeneric(site, doc, code, isNestedOverview: true);

    code.add(ApiPageCodeDedent());
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "}"));
}

private void appendCode(SiteRoot site, SymbolTree!(MaybeTemplated!DocStruct) doc, scope ref ApiPageDlangCode code, bool isNestedOverview = false)
{
    DocStruct model = doc.model.model;

    if(!isNestedOverview)
        appendModuleStatement(site, doc.module_, code);

    appendLinkage(model.linkage, code);
    appendVisibility(model.visibility, code);
    appendAggregateStorageClasses(model.storageClasses, code);
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "struct "));
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, doc.memberComponents[$-1]).asNavLink(
        site.groupNavStructsIdPath(doc.module_, doc.memberComponents)
    ));

    if(!doc.model.eponymousTemplate.isNull)
    {
        auto tpl = doc.model.eponymousTemplate.get;
        appendTemplateParams(tpl.originalParameters.length > 0 ? tpl.originalParameters : tpl.parameters, code, forceSingleLine: isNestedOverview);
    }

    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "{"));
    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeIndent());

    appendSymbolTreeMembersGeneric(site, doc, code, isNestedOverview: true);

    code.add(ApiPageCodeDedent());
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "}"));
}

private void appendCode(SiteRoot site, SymbolTree!(MaybeTemplated!DocUnion) doc, scope ref ApiPageDlangCode code, bool isNestedOverview = false)
{
    DocUnion model = doc.model.model;

    if(!isNestedOverview)
        appendModuleStatement(site, doc.module_, code);

    appendLinkage(model.linkage, code);
    appendVisibility(model.visibility, code);
    appendAggregateStorageClasses(model.storageClasses, code);
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "union "));
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, doc.memberComponents[$-1]).asNavLink(
        site.groupNavUnionsIdPath(doc.module_, doc.memberComponents)
    ));

    if(!doc.model.eponymousTemplate.isNull)
    {
        auto tpl = doc.model.eponymousTemplate.get;
        appendTemplateParams(tpl.originalParameters.length > 0 ? tpl.originalParameters : tpl.parameters, code, forceSingleLine: isNestedOverview);
    }

    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "{"));
    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeIndent());

    appendSymbolTreeMembersGeneric(site, doc, code, isNestedOverview: true);

    code.add(ApiPageCodeDedent());
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "}"));
}

private void appendCode(SiteRoot site, SymbolTree!DocTemplate doc, scope ref ApiPageDlangCode code, bool isNestedOverview = false)
{
    DocTemplate model = doc.model;

    if(!isNestedOverview)
        appendModuleStatement(site, doc.module_, code);

    appendLinkage(model.linkage, code);
    appendVisibility(model.visibility, code);
    appendAggregateStorageClasses(model.storageClasses, code);
    if(model.isMixin)
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "mixin "));
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "template "));
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, doc.memberComponents[$-1]).asNavLink(
        site.groupNavTemplatesIdPath(doc.module_, doc.memberComponents)
    ));

    appendTemplateParams(model.originalParameters.length > 0 ? model.originalParameters : model.parameters, code, forceSingleLine: isNestedOverview);

    if(doc.directChildCount == 0)
    {
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "{}"));
        return;
    }

    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "{"));
    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeIndent());

    appendSymbolTreeMembersGeneric(site, doc, code, isNestedOverview: true);

    code.add(ApiPageCodeDedent());
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "}"));
}

private void appendCode(SiteRoot site, SymbolLeaf!(MaybeTemplated!DocAlias) doc, scope ref ApiPageDlangCode code, bool isNestedOverview = false)
{
    DocAlias model = doc.model.model;

    if(!isNestedOverview)
        appendModuleStatement(site, doc.module_, code);

    appendLinkage(model.linkage, code);
    appendVisibility(model.visibility, code);
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "alias "));
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, doc.memberComponents[$-1]).asNavLink(
        site.groupNavAliasesIdPath(doc.module_, doc.memberComponents)
    ));

    if(!doc.model.eponymousTemplate.isNull)
    {
        auto tpl = doc.model.eponymousTemplate.get;
        appendTemplateParams(tpl.originalParameters.length > 0 ? tpl.originalParameters : tpl.parameters, code, forceSingleLine: isNestedOverview);
    }

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " = "));
    appendTypeRef(model.symbolRef, code, forceSingleLine: isNestedOverview);
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ";"));
}

private void appendCode(SiteRoot site, SymbolLeaf!(MaybeTemplated!DocFunction) doc, scope ref ApiPageDlangCode code, bool isNestedOverview = false)
{
    import std.algorithm : filter, canFind;

    DocFunction model = doc.model.model;

    if(!isNestedOverview)
        appendModuleStatement(site, doc.module_, code);

    appendLinkage(model.linkage, code);
    appendVisibility(model.visibility, code);

    foreach(class_; model.storageClasses.filter!(sc => STORAGE_CLASSES_BEFORE_FUNCTION_NAME.canFind(sc)))
    {
        if(class_ == DocStorageClass.auto_) // This is handled by the type ref rather than via storage classes
            continue;
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, (cast(string)class_) ~ " "));
    }

    if(model.funcType.returnType !is null)
        appendTypeRef(*model.funcType.returnType, code, forceSingleLine: isNestedOverview);
    else
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "auto"));

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, " "~doc.memberComponents[$-1]).asNavLink(
        site.groupNavFunctionsIdPath(doc.module_, doc.memberComponents)
    ));

    if(!doc.model.eponymousTemplate.isNull)
    {
        auto tpl = doc.model.eponymousTemplate.get;
        appendTemplateParams(tpl.originalParameters.length > 0 ? tpl.originalParameters : tpl.parameters, code, forceSingleLine: isNestedOverview);
    }

    appendRuntimeParams(model.funcType.parameters, code, forceSingleLine: isNestedOverview);
    foreach(class_; model.storageClasses.filter!(sc => !STORAGE_CLASSES_BEFORE_FUNCTION_NAME.canFind(sc)))
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, (cast(string)class_) ~ " "));
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ";"));
}

private void appendCode(SiteRoot site, SymbolLeaf!(MaybeTemplated!DocManifestConstant) doc, scope ref ApiPageDlangCode code, bool isNestedOverview = false)
{
    DocManifestConstant model = doc.model.model;

    if(!isNestedOverview)
        appendModuleStatement(site, doc.module_, code);

    appendVisibility(model.visibility, code);
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "enum "));

    if(!model.typeRef.isNull)
        appendTypeRef(model.typeRef.get, code, forceSingleLine: isNestedOverview);

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, " "~doc.memberComponents[$-1]).asNavLink(
        site.groupNavConstantsIdPath(doc.module_, doc.memberComponents)
    ));

    if(!doc.model.eponymousTemplate.isNull)
    {
        auto tpl = doc.model.eponymousTemplate.get;
        appendTemplateParams(tpl.originalParameters.length > 0 ? tpl.originalParameters : tpl.parameters, code, forceSingleLine: isNestedOverview);
    }

    // TODO: Maybe try to figure out when to use originalValueExpression instead
    if(!model.valueExpression.isNull)
    {
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " = "));
        appendExpression(model.valueExpression.get, code, forceSingleLine: isNestedOverview);
    }

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ";"));
}

private void appendCode(SiteRoot site, SymbolLeaf!DocEnum doc, scope ref ApiPageDlangCode code, bool isNestedOverview = false)
{
    import std.sumtype : match;

    DocEnum model = doc.model;

    if(!isNestedOverview)
        appendModuleStatement(site, doc.module_, code);

    appendVisibility(model.visibility, code);
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "enum "));

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, doc.memberComponents[$-1]).asNavLink(
        site.groupNavEnumsIdPath(doc.module_, doc.memberComponents)
    ));

    if(!model.baseTypeRef.isNull)
    {
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " : "));
        appendTypeRef(model.baseTypeRef.get, code, forceSingleLine: isNestedOverview);
    }

    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "{"));
    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeIndent());

    foreach(i, member; model.members)
    {
        DocManifestConstant manifestConstant = member.match!(
            (DocManifestConstant c) => c,
            (_) {
                assert(false, "bug: Can this be anything other than DocManifestConstant?");
                return DocManifestConstant.init;
            },
        );

        if(i > 0)
        {
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ", "));
            code.add(ApiPageCodeNewLine());
        }

        code.add(getOverviewCommentForCode(manifestConstant.comment));
        code.add(ApiPageCodeNewLine());
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, manifestConstant.name));

        if(!manifestConstant.valueExpression.isNull)
        {
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " = "));
            appendExpression(manifestConstant.valueExpression.get, code, forceSingleLine: true);
        }
    }

    code.add(ApiPageCodeDedent());
    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "}"));
}

private void appendCode(SiteRoot site, SymbolLeaf!DocVariable doc, scope ref ApiPageDlangCode code, bool isNestedOverview = false)
{
    DocVariable model = doc.model;

    if(!isNestedOverview)
        appendModuleStatement(site, doc.module_, code);

    appendLinkage(model.linkage, code);
    appendVisibility(model.visibility, code);
    appendAggregateStorageClasses(model.storageClasses, code);

    if(!model.typeRef.isNull)
        appendTypeRef(model.typeRef.get, code, forceSingleLine: isNestedOverview);
    else
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "auto"));

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, " "~doc.memberComponents[$-1]).asNavLink(
        site.groupNavVariablesIdPath(doc.module_, doc.memberComponents)
    ));

    if(!model.defaultValueExpression.isNull)
    {
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " = "));
        appendExpression(model.defaultValueExpression.get, code, forceSingleLine: isNestedOverview);
    }

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ";"));
}

private void appendRuntimeParams(DocRuntimeParameter[] params, scope ref ApiPageDlangCode code, bool forceSingleLine)
{
    import std.sumtype : match;

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "("));
    if(!forceSingleLine)
    {
        code.add(ApiPageCodeNewLine());
        code.add(ApiPageCodeIndent());
    }

    foreach(i, param; params)
    {
        if(i > 0)
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ", "));

        foreach(class_; param.storageClasses)
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, (cast(string)class_) ~ " "));

        appendTypeRef(param.typeRef, code, forceSingleLine);
        if(param.name != "__anonymous")
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.none, " "~param.name));

        if(!param.defaultValueExpression.isNull)
        {
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " = "));
            appendExpression(param.defaultValueExpression.get, code, forceSingleLine);
        }
    }

    if(!forceSingleLine)
    {
        code.add(ApiPageCodeNewLine());
        code.add(ApiPageCodeDedent());
    }
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ")"));
}

private void appendTemplateParams(DocTemplateParam[] params, scope ref ApiPageDlangCode code, bool forceSingleLine)
{
    import std.sumtype : match;

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "("));
    if(!forceSingleLine)
    {
        code.add(ApiPageCodeNewLine());
        code.add(ApiPageCodeIndent());
    }

    foreach(i, sumType; params)
    {
        if(i > 0)
        {
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ", "));

            if(!forceSingleLine)
                code.add(ApiPageCodeNewLine());
        }

        sumType.match!(
            (DocTemplateValueParam param){
                if(!param.valueType.isNull)
                {
                    appendTypeRef(param.valueType.get, code, forceSingleLine);
                    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.none, " "));
                }

                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, param.name));

                if(!param.specValue.isNull)
                {
                    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " : "));
                    appendExpression(param.specValue.get, code, forceSingleLine);
                }

                if(!param.defaultValue.isNull)
                {
                    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " = "));
                    appendExpression(param.defaultValue.get, code, forceSingleLine);
                }
            },
            (DocTemplateTypeParam param){
                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, param.name));

                if(!param.specType.isNull)
                {
                    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " : "));
                    appendTypeRef(param.specType.get, code, forceSingleLine);
                }

                if(!param.defaultType.isNull)
                {
                    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " = "));
                    appendTypeRef(param.defaultType.get, code, forceSingleLine);
                }
            },
            (DocTemplateAliasParam param){
                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "alias "));

                if(!param.specType.isNull)
                {
                    appendTypeRef(param.specType.get, code, forceSingleLine);
                    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.none, " "));
                }

                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, param.name));

                if(!param.specAlias.isNull)
                {
                    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " : "));
                    appendTypeRef(param.specAlias.get, code, forceSingleLine);
                }

                if(!param.defaultAlias.isNull)
                {
                    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, " = "));
                    appendTypeRef(param.defaultAlias.get, code, forceSingleLine);
                }
            },
            (DocTemplateTupleParam param){
                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.symbol, param.name));
                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.none, "..."));
            },
        );
    }

    if(!forceSingleLine)
    {
        code.add(ApiPageCodeNewLine());
        code.add(ApiPageCodeDedent());
    }
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ")"));
}

private void appendSymbolTreeMembersGeneric(DocModelT)(SiteRoot site, SymbolTree!DocModelT doc, scope ref ApiPageDlangCode code, bool isNestedOverview)
{
    foreach(i, item; doc.classes)
    {
        if(i > 0) code.add(ApiPageCodeNewLine());
        code.add(getOverviewCommentForCode(item.model.comment));
        code.add(ApiPageCodeNewLine());
        appendCode(site, item, code, isNestedOverview);
    }
    if(doc.classes.length > 0) { code.add(ApiPageCodeNewLine()); code.add(ApiPageCodeNewLine()); }

    foreach(i, item; doc.structs)
    {
        if(i > 0) code.add(ApiPageCodeNewLine());
        code.add(getOverviewCommentForCode(item.model.comment));
        code.add(ApiPageCodeNewLine());
        appendCode(site, item, code, isNestedOverview);
    }
    if(doc.structs.length > 0) { code.add(ApiPageCodeNewLine()); code.add(ApiPageCodeNewLine()); }

    foreach(i, item; doc.unions)
    {
        if(i > 0) code.add(ApiPageCodeNewLine());
        code.add(getOverviewCommentForCode(item.model.comment));
        code.add(ApiPageCodeNewLine());
        appendCode(site, item, code, isNestedOverview);
    }
    if(doc.unions.length > 0) { code.add(ApiPageCodeNewLine()); code.add(ApiPageCodeNewLine()); }

    foreach(i, item; doc.templates)
    {
        if(i > 0) code.add(ApiPageCodeNewLine());
        code.add(getOverviewCommentForCode(item.model.comment));
        code.add(ApiPageCodeNewLine());
        appendCode(site, item, code, isNestedOverview);
    }
    if(doc.templates.length > 0) { code.add(ApiPageCodeNewLine()); code.add(ApiPageCodeNewLine()); }

    foreach(i, item; doc.aliases)
    {
        if(i > 0) code.add(ApiPageCodeNewLine());
        code.add(getOverviewCommentForCode(item.model.comment));
        code.add(ApiPageCodeNewLine());
        appendCode(site, item, code, isNestedOverview);
    }
    if(doc.aliases.length > 0) { code.add(ApiPageCodeNewLine()); code.add(ApiPageCodeNewLine()); }

    foreach(i, item; doc.functions)
    {
        if(i > 0) code.add(ApiPageCodeNewLine());
        code.add(getOverviewCommentForCode(item.model.comment));
        code.add(ApiPageCodeNewLine());
        appendCode(site, item, code, isNestedOverview);
    }
    if(doc.functions.length > 0) { code.add(ApiPageCodeNewLine()); code.add(ApiPageCodeNewLine()); }

    foreach(i, item; doc.constants)
    {
        if(i > 0) code.add(ApiPageCodeNewLine());
        code.add(getOverviewCommentForCode(item.model.comment));
        code.add(ApiPageCodeNewLine());
        appendCode(site, item, code, isNestedOverview);
    }
    if(doc.constants.length > 0) { code.add(ApiPageCodeNewLine()); code.add(ApiPageCodeNewLine()); }

    foreach(i, item; doc.enums)
    {
        if(i > 0) code.add(ApiPageCodeNewLine());
        code.add(getOverviewCommentForCode(item.model.comment));
        code.add(ApiPageCodeNewLine());
        appendCode(site, item, code, isNestedOverview);
    }
    if(doc.enums.length > 0) { code.add(ApiPageCodeNewLine()); code.add(ApiPageCodeNewLine()); }

    foreach(i, item; doc.variables)
    {
        if(i > 0) code.add(ApiPageCodeNewLine());
        code.add(getOverviewCommentForCode(item.model.comment));
        code.add(ApiPageCodeNewLine());
        appendCode(site, item, code, isNestedOverview);
    }
    if(doc.variables.length > 0) { code.add(ApiPageCodeNewLine()); code.add(ApiPageCodeNewLine()); }
}

private void appendTypeRef(DocTypeRef typeRef, scope ref ApiPageDlangCode code, bool forceSingleLine = false)
{
    import std.sumtype : match;

    // TODO: Figure out situations where it's better to use the original type ref, e.g. for aliases?
    auto raw = typeRef.raw;

    const isFunction = raw.match!((DocFunctionType _) => true, (_) => false);

    if(!isFunction)
    {
        foreach(class_; typeRef.storageClasses)
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, (cast(string)class_) ~ " "));
    }

    void appendSymbolRef(DocSymbolReference type){
        const wasResolved = type.moduleFqnComponents.length > 0;
        string[] symbolStack;

        foreach(i, item; type.items)
        {
            if(i > 0)
                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "."));

            item.match!(
                (DocSymbolDirectReference symbol){
                    symbolStack ~= symbol.symbolName;

                    auto text = ApiPageCodeText(ApiPageCodeText.Syntax.symbol, symbol.symbolName);
                    if(wasResolved)
                        code.add(text.asNavLink(type.moduleFqnComponents ~ symbolStack));
                    else
                        code.add(text.asCodeComponent);
                },
                (DocSymbolUnhandled symbol){
                    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "???"));
                },
                (DocSymbolInstanceReference symbol){
                    symbolStack ~= symbol.symbolName;

                    auto text = ApiPageCodeText(ApiPageCodeText.Syntax.symbol, symbol.symbolName);
                    if(wasResolved)
                        code.add(text.asNavLink(type.moduleFqnComponents ~ symbolStack));
                    else
                        code.add(text.asCodeComponent);

                    const useSingleLine = forceSingleLine || false; // TODO: Figure out conditions for when to split to multiple lines that actually looks good.
                    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "!("));
                    if(!useSingleLine)
                    {
                        code.add(ApiPageCodeNewLine());
                        code.add(ApiPageCodeIndent());
                    }

                    foreach(i, sumType; symbol.parameters)
                    {
                        if(i > 0)
                            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ", "));

                        sumType.match!(
                            (DocExpression param){
                                appendExpression(param, code, forceSingleLine);
                            },
                            (DocSymbolReference* param){
                                appendSymbolRef(*param);
                            },
                            (DocTypeRef* param){
                                appendTypeRef(*param, code, forceSingleLine);
                            },
                        );
                    }

                    if(!useSingleLine)
                    {
                        code.add(ApiPageCodeNewLine());
                        code.add(ApiPageCodeDedent());
                    }
                    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ")"));
                },
            );
        }
    }

    raw.match!(
        (DocSymbolReference type){
            appendSymbolRef(type);
        },
        (DocArrayType type){
            appendTypeRef(*type.underlyingTypeRef, code, forceSingleLine);
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "[]"));
        },
        (DocAssociativeArrayType type){
            appendTypeRef(*type.valueTypeRef, code, forceSingleLine);
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "["));
            appendTypeRef(*type.keyTypeRef, code, forceSingleLine: true);
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "]"));
        },
        (DocStaticArrayType type){
            appendTypeRef(*type.underlyingTypeRef, code, forceSingleLine);
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "["));
            appendExpression(type.arraySizeExpression, code, forceSingleLine: true);
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "]"));
        },
        (DocBasicType type){
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, type.name));
        },
        (DocPointerType type){
            appendTypeRef(*type.underlyingTypeRef, code, forceSingleLine);
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "*"));
        },
        (DocFunctionType type){
            if(type.returnType !is null)
                appendTypeRef(*type.returnType, code, forceSingleLine);
            else
                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "auto"));

            if(type.isDelegate)
                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, " delegate"));
            else
                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, " function"));

            appendRuntimeParams(type.parameters, code, forceSingleLine);

            if(typeRef.storageClasses.length > 0)
                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.none, " "));

            foreach(class_; typeRef.storageClasses)
                code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, (cast(string)class_) ~ " "));
        },
    );
}

private void appendExpression(DocExpression exp, scope ref ApiPageDlangCode code, bool forceSingleLine = false)
{
    import std.sumtype : match;

    exp.match!(
        (DocFallbackExpression expression){
            code.add(ApiPageCodeText(ApiPageCodeText.Syntax.expression, expression.renderedCode));
        }
    );
}

private void appendModuleStatement(SiteRoot site, DocModule mod, scope ref ApiPageDlangCode code)
{
    import std.string : join;

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "module "));
    code.add(ApiPageCodeText(text: mod.fqnComponents.join(".")).asNavLink(mod.fqnComponents ~ site.groupNavIndexId));
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ";"));
    code.add(ApiPageCodeNewLine());
    code.add(ApiPageCodeNewLine());
}

private void appendLinkage(DocLinkage linkage, scope ref ApiPageDlangCode code)
{
    if(linkage == DocLinkage.d || linkage == DocLinkage.default_)
        return;

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, "extern"));
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, "("));
    final switch(linkage) with(DocLinkage)
    {
        case default_:
        case d:
            assert(false);
    
        case c:
            code.add(ApiPageCodeText(text: "C"));
            break;
        case cpp:
            code.add(ApiPageCodeText(text: "C++"));
            break;
        case windows:
            code.add(ApiPageCodeText(text: "Windows"));
            break;
        case objc:
            code.add(ApiPageCodeText(text: "Objective-C"));
            break;
        case system:
            code.add(ApiPageCodeText(text: "System"));
            break;
    }
    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.operator, ") "));
}

private void appendVisibility(DocVisibility vis, scope ref ApiPageDlangCode code)
{
    if(vis == DocVisibility.public_ || vis == DocVisibility.undefined)
        return;

    code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, cast(string)vis ~ " "));
}

private void appendAggregateStorageClasses(DocStorageClass[] classes, scope ref ApiPageDlangCode code)
{
    foreach(class_; classes)
        code.add(ApiPageCodeText(ApiPageCodeText.Syntax.keyword, (cast(string)class_) ~ " "));
}

/++ Doc model helpers ++/

// If a DocTemplate is determined to be eponymous, then it'll get collapsed into this type so it's easier to handle optionally-templated types.
private struct MaybeTemplated(DocModelT)
{
    import std.typecons : Nullable;

    DocModelT model;
    Nullable!DocTemplate eponymousTemplate;

    this(DocModelT model)
    {
        this.model = model;
    }

    this(DocModelT model, DocTemplate eponymousTemplate)
    {
        this.model = model;
        this.eponymousTemplate = eponymousTemplate;
    }

    Nullable!DocComment comment() => (this.model.comment.isNull && !this.eponymousTemplate.isNull)
        ? this.eponymousTemplate.get.comment
        : this.model.comment;
}

private struct SymbolLeaf(DocModelT)
{
    DocModule module_;
    DocModelT model;
    string[] memberComponents; // `mod1` -> []; `mod1.Class` -> ["Class"]; `mod1.Class.Subclass` -> ["Class", "Subclass"];

    static typeof(this) fromModel(DocModule parentModule, DocModelT inputModel, string[] parentMemberComponents = [])
    {
        import std.sumtype : match;

        typeof(this) tree;
        tree.module_ = parentModule;
        tree.model = inputModel;

        static if(is(DocModelT : MaybeTemplated!T, T))
            auto model = inputModel.model;
        else
            auto model = inputModel;

        static if(__traits(hasMember, typeof(model), "name"))
            tree.memberComponents = parentMemberComponents ~ model.name;
        else
            assert(tree.memberComponents.length == 0);

        return tree;
    }
}

private struct SymbolTree(DocModelT)
{
    DocModule module_;
    DocModelT model;
    string[] memberComponents; // `mod1` -> []; `mod1.Class` -> ["Class"]; `mod1.Class.Subclass` -> ["Class", "Subclass"];

    SymbolTree!(MaybeTemplated!DocClass)[] classes;
    SymbolTree!(MaybeTemplated!DocStruct)[] structs;
    SymbolTree!(MaybeTemplated!DocUnion)[] unions;
    SymbolTree!DocTemplate[] templates; // Generally: Non-eponymous or eponymous but still has multiple members.

    SymbolLeaf!(MaybeTemplated!DocAlias)[] aliases;
    SymbolLeaf!(MaybeTemplated!DocFunction)[] functions;
    SymbolLeaf!(MaybeTemplated!DocManifestConstant)[] constants;
    SymbolLeaf!DocEnum[] enums;
    SymbolLeaf!DocVariable[] variables;

    size_t directChildCount() =>
        this.classes.length
        + this.structs.length
        + this.unions.length
        + this.templates.length
        + this.aliases.length
        + this.functions.length
        + this.constants.length
        + this.enums.length
        + this.variables.length;

    void sortByName()
    {
        import std.algorithm : sort, multiSort;
        import std.string    : join;

        this.classes.multiSort!((a,b) => a.memberComponents.length < b.memberComponents.length, (a,b) => a.memberComponents.join(".") < b.memberComponents.join("."));
        this.structs.multiSort!((a,b) => a.memberComponents.length < b.memberComponents.length, (a,b) => a.memberComponents.join(".") < b.memberComponents.join("."));
        this.unions.multiSort!((a,b) => a.memberComponents.length < b.memberComponents.length, (a,b) => a.memberComponents.join(".") < b.memberComponents.join("."));
        this.templates.multiSort!((a,b) => a.memberComponents.length < b.memberComponents.length, (a,b) => a.memberComponents.join(".") < b.memberComponents.join("."));
        this.aliases.sort!((a,b) => a.model.model.name < b.model.model.name);
        this.functions.sort!((a,b) => a.model.model.name < b.model.model.name);
        this.constants.sort!((a,b) => a.model.model.name < b.model.model.name);
        this.enums.sort!((a,b) => a.model.name < b.model.name);
        this.variables.sort!((a,b) => a.model.name < b.model.name);

        foreach(tree; this.classes) tree.sortByName();
        foreach(tree; this.structs) tree.sortByName();
        foreach(tree; this.unions) tree.sortByName();
        foreach(tree; this.templates) tree.sortByName();
    }

    static typeof(this) fromModel(DocModule parentModule, DocModelT inputModel, string[] parentMemberComponents = [])
    {
        import std.algorithm : startsWith;
        import std.sumtype   : match;

        typeof(this) tree;
        tree.module_ = parentModule;
        tree.model = inputModel;

        static if(is(DocModelT : MaybeTemplated!T, T))
            auto model = inputModel.model;
        else
            auto model = inputModel;

        static if(__traits(hasMember, typeof(model), "name"))
            tree.memberComponents = parentMemberComponents ~ model.name;
        else
            assert(tree.memberComponents.length == 0);

        // Special case DocModelRoot
        static if(is(DocModelT == DocModelRoot))
        {
            auto nestedTypes = model.module_.nestedTypes;
            auto unaryTypes  = model.module_.members;
        }
        else
        {
            auto nestedTypes = model.nestedTypes;
            auto unaryTypes  = model.members;
        }

        static bool shouldIgnore(T)(T value)
        {
            static if(__traits(hasMember, T, "visibility"))
                return !(value.visibility == DocVisibility.public_ || value.visibility == DocVisibility.undefined);
            else
                return false;
        }

        foreach(aggregate; nestedTypes)
        {
            aggregate.match!(
                (DocStruct item) {
                    if(shouldIgnore(item)) return;
                    auto notTemplated = MaybeTemplated!DocStruct(item);
                    tree.structs ~= typeof(tree.structs[0]).fromModel(parentModule, notTemplated, tree.memberComponents);
                },
                (DocClass item) {
                    if(shouldIgnore(item)) return;
                    auto notTemplated = MaybeTemplated!DocClass(item);
                    tree.classes ~= typeof(tree.classes[0]).fromModel(parentModule, notTemplated, tree.memberComponents);
                },
                (DocUnion item) {
                    if(shouldIgnore(item)) return;
                    auto notTemplated = MaybeTemplated!DocUnion(item);
                    tree.unions ~= typeof(tree.unions[0]).fromModel(parentModule, notTemplated, tree.memberComponents);
                },
                (DocEnum item) {
                    if(shouldIgnore(item)) return;
                    tree.enums ~= typeof(tree.enums[0]).fromModel(parentModule, item, tree.memberComponents);
                },
                (DocTemplate item) {
                    if(shouldIgnore(item)) return;
                    // If the template has only one member; that member has the same name as the template, and that member
                    // isn't also a DocTemplate, then treat it as eponymous.
                    const hasOneMember = (item.members.length + item.nestedTypes.length == 1);
                    const hasSameName =
                        item.members.length > 0
                        ? item.members[0].match!((member) => member.name == item.name)
                        : item.nestedTypes.length > 0 
                            ? item.nestedTypes[0].match!((type) => type.name == item.name)
                            : false;
                    
                    // I _could_ DRY this but it's more of a hassle than it's worth IMO.
                    if(hasOneMember && hasSameName)
                    {
                        const wasTemplatable =
                            item.members.length > 0
                            ? item.members[0].match!(
                                (DocManifestConstant member) {
                                    if(shouldIgnore(item)) return false;
                                    auto templated = MaybeTemplated!DocManifestConstant(member, item);
                                    tree.constants ~= typeof(tree.constants[0]).fromModel(parentModule, templated, tree.memberComponents);
                                    return true;
                                },
                                (DocFunction member) {
                                    if(shouldIgnore(item)) return false;
                                    if(item.name.startsWith("__")) return false;
                                    auto templated = MaybeTemplated!DocFunction(member, item);
                                    tree.functions ~= typeof(tree.functions[0]).fromModel(parentModule, templated, tree.memberComponents);
                                    return true;
                                },
                                (DocAlias member) {
                                    if(shouldIgnore(item)) return false;
                                    auto templated = MaybeTemplated!DocAlias(member, item);
                                    tree.aliases ~= typeof(tree.aliases[0]).fromModel(parentModule, templated, tree.memberComponents);
                                    return true;
                                },
                                (_) => false,
                            )
                            : item.nestedTypes[0].match!(
                                (DocStruct type) {
                                    if(shouldIgnore(item)) return false;
                                    auto templated = MaybeTemplated!DocStruct(type, item);
                                    tree.structs ~= typeof(tree.structs[0]).fromModel(parentModule, templated, tree.memberComponents);
                                    return true;
                                },
                                (DocClass type) {
                                    if(shouldIgnore(item)) return false;
                                    auto templated = MaybeTemplated!DocClass(type, item);
                                    tree.classes ~= typeof(tree.classes[0]).fromModel(parentModule, templated, tree.memberComponents);
                                    return true;
                                },
                                (DocUnion type) {
                                    if(shouldIgnore(item)) return false;
                                    auto templated = MaybeTemplated!DocUnion(type, item);
                                    tree.unions ~= typeof(tree.unions[0]).fromModel(parentModule, templated, tree.memberComponents);
                                    return true;
                                },
                                (_) => false,
                            );

                        if(wasTemplatable)
                            return;
                    }

                    // Otherwise just treat it as a straight up template.
                    tree.templates ~= typeof(tree.templates[0]).fromModel(parentModule, item, tree.memberComponents);
                },
            );
        }

        foreach(unary; unaryTypes)
        {
            unary.match!(
                (DocManifestConstant item) {
                    if(shouldIgnore(item)) return;
                    auto notTemplated = MaybeTemplated!DocManifestConstant(item);
                    tree.constants ~= typeof(tree.constants[0]).fromModel(parentModule, notTemplated, tree.memberComponents);
                },
                (DocFunction item) {
                    if(shouldIgnore(item)) return;
                    if(item.name.startsWith("__")) return;
                    auto notTemplated = MaybeTemplated!DocFunction(item);
                    tree.functions ~= typeof(tree.functions[0]).fromModel(parentModule, notTemplated, tree.memberComponents);
                },
                (DocAlias item) {
                    if(shouldIgnore(item)) return;
                    auto notTemplated = MaybeTemplated!DocAlias(item);
                    tree.aliases ~= typeof(tree.aliases[0]).fromModel(parentModule, notTemplated, tree.memberComponents);
                },
                (DocVariable item) {
                    if(shouldIgnore(item)) return;
                    tree.variables ~= typeof(tree.variables[0]).fromModel(parentModule, item, tree.memberComponents);
                },
                (DocRuntimeParameter item) { /* This shouldn't ever really actually happen... why is the doc model even like this lol? */ },
            );
        }

        return tree;
    }
}

/++ File helpers ++/

private void emitFile(SiteRoot site, string[] pathComponents, const(char)[] text)
{
    import std.file : writeText = write, mkdirRecurse;
    import std.path : dirName, buildNormalizedPath;

    const path = buildNormalizedPath([site.stagingDir] ~ pathComponents);

    infof("emitting file: %s", path);

    mkdirRecurse(path.dirName);
    writeText(path, text);
}

package void emitFile(string path, const(char)[] text)
{
    import std.file : writeText = write, mkdirRecurse;
    import std.path : dirName;

    infof("emitting file: %s", path);

    mkdirRecurse(path.dirName);
    writeText(path, text);
}

/++ Url helpers ++/

private string rootGroupIndexUrl(RootGroup group)
{
    import std.path : buildPath;

    // Assume the server can resolve e.g. `/api-reference` to `/api-reference/index.html`
    return buildPath(["/", group.groupUrlName]);
}