name: Release

# on:
#   release:
#     types: [released]

on:
  push:
    branches:
      - master

jobs:
  build_marmos:
    name: Build Marmos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-marmos

  build_and_release_npm:
    name: Build and Release marmos-docfx
    runs-on: ubuntu-latest
    needs: build_marmos
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: marmos-executables

      - name: Generate marmos.ts
        run: ./marmos generate-typescript --output-file dogfood/typescript/src/marmos.ts

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: ./dogfood/typescript/pnpm-lock.yaml

      - name: Install Dependencies
        working-directory: dogfood/typescript
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: dogfood/typescript
        run: pnpm run build

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # TAG=$(echo "${{ github.event.release.tag_name }}" | sed 's/v//') # Remove the 'v' prefix
        run: |
          TAG=$(echo v0.0.1 | sed 's/v//') # Remove the 'v' prefix
          npm version --allow-same-version --no-commit-hooks --no-git-tag-version $TAG
          npm publish --access public