name: Unittests

on:
  pull_request:
  push:

jobs:
  linux_test:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tooling (apt)
        shell: sh
        run: sudo apt update && sudo apt install -y python3-pip libsodium-dev

      - name: Install Tooling (pip)
        shell: sh
        run: pip3 install meson ninja

      - name: Install Dlang
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest

      - name: Configure Meson
        shell: sh
        run: meson setup build --prefix $(pwd)/install

      - name: Build
        run: meson compile -C build

      - name: Test
        run: meson test -C build
